export const REAL_UP_ORGANIZATIONS = {
  'Marquette County': [
    { name: "Northern Michigan University Foundation", ein: "38-6005298", sector: "Education" },
    { name: "Upper Peninsula Health Plan", ein: "38-3404789", sector: "Health Services" },
    { name: "Superior Watershed Partnership", ein: "38-3454790", sector: "Environment & Animals" },
    { name: "Marquette County Community Foundation", ein: "38-2834521", sector: "Public & Societal Benefit" },
    { name: "Great Lakes Recovery Centers", ein: "38-2194852", sector: "Health Services" },
    { name: "Community Action Alger-Marquette", ein: "38-1764321", sector: "Human Services" },
    { name: "Upper Peninsula Children's Museum", ein: "38-3124567", sector: "Arts & Culture" },
    { name: "Peter White Public Library", ein: "38-6001234", sector: "Education" },
    { name: "St. Vincent de Paul Society Marquette", ein: "38-1234567", sector: "Human Services" },
    { name: "YMCA of Marquette County", ein: "38-2345678", sector: "Human Services" },
    { name: "Lake Superior Hospice Association", ein: "38-3456789", sector: "Health Services" },
    { name: "Marquette Maritime Museum", ein: "38-4567890", sector: "Arts & Culture" },
    { name: "UP Health Care Solutions", ein: "38-3567812", sector: "Health Services" },
    { name: "Janzen House Inc", ein: "38-2211443", sector: "Human Services" },
    { name: "Room at the Inn", ein: "38-2998877", sector: "Human Services" },
    { name: "Upper Peninsula Animal Welfare Shelter", ein: "38-1882233", sector: "Environment & Animals" },
    { name: "Marquette Regional History Center", ein: "38-0992211", sector: "Arts & Culture" },
    { name: "Trillium House", ein: "38-4433221", sector: "Health Services" },
    { name: "Lake Superior Community Partnership", ein: "38-2288331", sector: "Public & Societal Benefit" },
    { name: "United Way of Marquette County", ein: "38-0772211", sector: "Human Services" },
    { name: "Marquette Symphony Orchestra", ein: "38-1122998", sector: "Arts & Culture" },
    { name: "Fresh Coast Film Festival", ein: "38-9988112", sector: "Arts & Culture" },
    { name: "Marquette Food Co-op (NP Education)", ein: "38-3344112", sector: "Education" },
    { name: "Northwoods AirLife", ein: "38-5566778", sector: "Health Services" },
    { name: "Upper Peninsula Land Conservancy", ein: "38-1112233", sector: "Environment & Animals" },
    { name: "StartUP Marquette", ein: "38-9900112", sector: "Public & Societal Benefit" },
    { name: "U.P. Cybersecurity Institute", ein: "38-7766221", sector: "Education" },
    { name: "Northern Center for Lifelong Learning", ein: "38-8833441", sector: "Education" },
    { name: "Marquette Choral Society", ein: "38-2233991", sector: "Arts & Culture" },
    { name: "Lake Superior Theatre", ein: "38-1155442", sector: "Arts & Culture" }
  ],
  'Houghton County': [
    { name: "Michigan Tech Fund", ein: "38-6052820", sector: "Education" },
    { name: "Portage Health Foundation", ein: "38-3012345", sector: "Health Services" },
    { name: "Keweenaw Land Trust", ein: "38-3123456", sector: "Environment & Animals" },
    { name: "Copper Country Community Arts Council", ein: "38-2134567", sector: "Arts & Culture" },
    { name: "Little Brothers Friends of the Elderly", ein: "38-1987654", sector: "Human Services" },
    { name: "Keweenaw National Historical Park Advisory", ein: "38-4561234", sector: "Public & Societal Benefit" },
    { name: "Dial Help Inc", ein: "38-2023456", sector: "Human Services" },
    { name: "Omega House", ein: "38-3034567", sector: "Health Services" },
    { name: "31 Backpack Program", ein: "38-4445556", sector: "Human Services" },
    { name: "Houghton County Historical Society", ein: "38-2223334", sector: "Arts & Culture" },
    { name: "Barbara Kettle Gundlach Shelter", ein: "38-1110001", sector: "Human Services" },
    { name: "Keweenaw Community Foundation", ein: "38-9988776", sector: "Public & Societal Benefit" },
    { name: "Finlandia University (Legacy Trust)", ein: "38-0099112", sector: "Education" },
    { name: "Copper Country Habitat for Humanity", ein: "38-3344221", sector: "Human Services" },
    { name: "Keweenaw Nordic Ski Club", ein: "38-5544112", sector: "Other" },
    { name: "Swedetown Trails Club", ein: "38-2288334", sector: "Other" },
    { name: "Calumet Theatre Company", ein: "38-1199223", sector: "Arts & Culture" },
    { name: "Main Street Calumet", ein: "38-4455668", sector: "Public & Societal Benefit" },
    { name: "Houghton Public Library", ein: "38-0022334", sector: "Education" },
    { name: "Keweenaw Heritage Center", ein: "38-7711223", sector: "Arts & Culture" }
  ],
  'Chippewa County': [
    { name: "Lake Superior State University Foundation", ein: "38-2845671", sector: "Education" },
    { name: "United Way of the Eastern UP", ein: "38-1122334", sector: "Human Services" },
    { name: "War Memorial Hospital", ein: "38-0987654", sector: "Health Services" },
    { name: "Sault Ste Marie Tribe (NP Gov)", ein: "38-6004561", sector: "Public & Societal Benefit" },
    { name: "Bayliss Public Library", ein: "38-7766554", sector: "Education" },
    { name: "Hiawatha Traditional Music Council", ein: "38-1239874", sector: "Arts & Culture" },
    { name: "EUP Community Dispute Resolution", ein: "38-4455119", sector: "Public & Societal Benefit" },
    { name: "Chippewa County Community Foundation", ein: "38-0099443", sector: "Public & Societal Benefit" },
    { name: "Diane Peppler Resource Center", ein: "38-2223344", sector: "Human Services" },
    { name: "Great Lakes Shipwreck Historical Society", ein: "38-1112223", sector: "Arts & Culture" },
    { name: "St. Mary's Catholic School", ein: "38-3334445", sector: "Education" },
    { name: "War Memorial Hospital Foundation", ein: "38-5556667", sector: "Health Services" },
    { name: "Sault Area Art Village", ein: "38-0011224", sector: "Arts & Culture" },
    { name: "Pickford Community Library", ein: "38-3344556", sector: "Education" },
    { name: "EUP Regional Planning", ein: "38-9988772", sector: "Public & Societal Benefit" }
  ],
  'Delta County': [
    { name: "OSF St Francis Hospital", ein: "38-1212343", sector: "Health Services" },
    { name: "Community Foundation for Delta County", ein: "38-3232454", sector: "Public & Societal Benefit" },
    { name: "Bay de Noc CC Foundation", ein: "38-2929383", sector: "Education" },
    { name: "Delta County Economic Development", ein: "38-4455667", sector: "Public & Societal Benefit" },
    { name: "William Bonifas Arts Center", ein: "38-1122883", sector: "Arts & Culture" },
    { name: "Delta County Cancer Alliance", ein: "38-9988221", sector: "Health Services" },
    { name: "Hope at the Inn", ein: "38-3344559", sector: "Human Services" },
    { name: "Escanaba Public Library", ein: "38-7766112", sector: "Education" },
    { name: "St. Vincent de Paul - Escanaba", ein: "38-4445551", sector: "Human Services" },
    { name: "Delta Animal Shelter", ein: "38-2233449", sector: "Environment & Animals" },
    { name: "Player's de Noc", ein: "38-0099119", sector: "Arts & Culture" },
    { name: "Gladstone Public Library Trust", ein: "38-1122338", sector: "Education" }
  ],
  'Menominee County': [
    { name: "Aurora Medical Center - Menominee", ein: "38-1234123", sector: "Health Services" },
    { name: "Menominee Area Community Foundation", ein: "38-2233112", sector: "Public & Societal Benefit" },
    { name: "Menominee County Historical Society", ein: "38-3344223", sector: "Arts & Culture" },
    { name: "DAR Boys and Girls Club", ein: "38-4455334", sector: "Human Services" },
    { name: "Menominee Animal Shelter", ein: "38-5566445", sector: "Environment & Animals" },
    { name: "Bridges of Hope Menominee", ein: "38-6677556", sector: "Human Services" },
    { name: "Mid-County Rescue 114", ein: "38-7788667", sector: "Health Services" },
    { name: "Menominee Downtown Development", ein: "38-8899778", sector: "Public & Societal Benefit" },
    { name: "Spies Public Library", ein: "38-1100223", sector: "Education" },
    { name: "Menominee Opera House Preservation", ein: "38-4433229", sector: "Arts & Culture" }
  ],
  'Dickinson County': [
    { name: "Marshfield Medical Center-Dickinson", ein: "38-4455112", sector: "Health Services" },
    { name: "Iron Mountain Area Schools Foundation", ein: "38-3344556", sector: "Education" },
    { name: "Dickinson Area Community Foundation", ein: "38-1122331", sector: "Public & Societal Benefit" },
    { name: "Cornish Pump Engine & Mining Museum", ein: "38-9988113", sector: "Arts & Culture" },
    { name: "Almost Home Animal Shelter", ein: "38-5566771", sector: "Environment & Animals" },
    { name: "United Way of Dickinson County", ein: "38-6677882", sector: "Human Services" },
    { name: "Kingsford Schools Foundation", ein: "38-1122330", sector: "Education" },
    { name: "Dickinson County Library", ein: "38-4455660", sector: "Education" },
    { name: "Northwoods Manufacturing", ein: "38-2233440", sector: "Other" },
    { name: "Iron Mountain Downtown Assoc", ein: "38-5566770", sector: "Public & Societal Benefit" }
  ],
  'Gogebic County': [
    { name: "Aspirus Ironwood Hospital", ein: "38-7788991", sector: "Health Services" },
    { name: "Gogebic CC Foundation", ein: "38-6655443", sector: "Education" },
    { name: "Historic Ironwood Theatre", ein: "38-1122339", sector: "Arts & Culture" },
    { name: "DOVE Inc (Domestic Violence)", ein: "38-4455661", sector: "Human Services" },
    { name: "Gogebic Range United Way", ein: "38-9988771", sector: "Human Services" },
    { name: "Western UP Convention Bureau", ein: "38-2233441", sector: "Public & Societal Benefit" },
    { name: "Iron County Housing Council (Gogebic)", ein: "38-3344550", sector: "Human Services" },
    { name: "Ironwood Public Library", ein: "38-7788990", sector: "Education" }
  ],
  'Alger County': [
    { name: "Munising Memorial Hospital", ein: "38-5544332", sector: "Health Services" },
    { name: "Pictured Rocks Interpretive Assoc", ein: "38-6677889", sector: "Arts & Culture" },
    { name: "Alger Regional Community Foundation", ein: "38-3322110", sector: "Public & Societal Benefit" },
    { name: "Valley Spur (Friends of)", ein: "38-4455662", sector: "Environment & Animals" },
    { name: "Munising Public Library Trust", ein: "38-1122334", sector: "Education" },
    { name: "Alger County Historical Society", ein: "38-5566772", sector: "Arts & Culture" },
    { name: "Great Lakes Recovery (Alger Branch)", ein: "38-2233442", sector: "Health Services" }
  ],
  'Iron County': [
    { name: "Aspirus Iron River Hospital", ein: "38-2211334", sector: "Health Services" },
    { name: "Iron County Housing Commission", ein: "38-3322445", sector: "Human Services" },
    { name: "Iron County Museum", ein: "38-4433556", sector: "Arts & Culture" },
    { name: "West Iron County Education Foundation", ein: "38-5544667", sector: "Education" },
    { name: "Iron County Community Foundation", ein: "38-6655778", sector: "Public & Societal Benefit" },
    { name: "Windsor Center (Iron River)", ein: "38-1122333", sector: "Arts & Culture" },
    { name: "Iron County Animal Control NP", ein: "38-4455663", sector: "Environment & Animals" }
  ],
  'Mackinac County': [
    { name: "Mackinac Straits Health System", ein: "38-8899001", sector: "Health Services" },
    { name: "Mackinac Island Community Foundation", ein: "38-1122556", sector: "Public & Societal Benefit" },
    { name: "Mackinac State Historic Parks", ein: "38-6098765", sector: "Arts & Culture" },
    { name: "Mackinac Island Public Library", ein: "38-3344551", sector: "Education" },
    { name: "Les Cheneaux Historical Assoc", ein: "38-9988775", sector: "Arts & Culture" },
    { name: "Mackinac Straits Hospital Found", ein: "38-2233443", sector: "Health Services" },
    { name: "St. Ignace Public Library", ein: "38-5566773", sector: "Education" }
  ],
  'Baraga County': [
    { name: "Baraga County Memorial Hospital", ein: "38-1122441", sector: "Health Services" },
    { name: "KBIC Health Center (Tribal NP)", ein: "38-2233552", sector: "Health Services" },
    { name: "Baraga County Community Foundation", ein: "38-3344663", sector: "Public & Societal Benefit" },
    { name: "Copper Country Mental Health Baraga", ein: "38-4455774", sector: "Human Services" },
    { name: "L'Anse Public Library", ein: "38-5566774", sector: "Education" },
    { name: "Friends of the Baraga State Park", ein: "38-2233444", sector: "Environment & Animals" }
  ],
  'Schoolcraft County': [
    { name: "Schoolcraft Memorial Hospital", ein: "38-2233445", sector: "Health Services" },
    { name: "Manistique Area Schools Foundation", ein: "38-1199887", sector: "Education" },
    { name: "Schoolcraft County Community Foundation", ein: "38-3344552", sector: "Public & Societal Benefit" },
    { name: "Eva Burrell Animal Shelter", ein: "38-5566779", sector: "Environment & Animals" },
    { name: "Manistique Public Library", ein: "38-2233445", sector: "Education" },
    { name: "Schoolcraft Historical Society", ein: "38-4455664", sector: "Arts & Culture" }
  ],
  'Luce County': [
    { name: "Helen Newberry Joy Hospital", ein: "38-1122335", sector: "Health Services" },
    { name: "Luce County Economic Development", ein: "38-2233446", sector: "Public & Societal Benefit" },
    { name: "Tahquamenon Area Community Foundation", ein: "38-3344557", sector: "Public & Societal Benefit" },
    { name: "Newberry Public Library", ein: "38-4455668", sector: "Education" },
    { name: "Luce County Historical Museum", ein: "38-5566775", sector: "Arts & Culture" }
  ],
  'Ontonagon County': [
    { name: "Aspirus Ontonagon Hospital", ein: "38-1122336", sector: "Health Services" },
    { name: "Ontonagon County Historical Society", ein: "38-2233447", sector: "Arts & Culture" },
    { name: "Ontonagon Area Schools Foundation", ein: "38-3344558", sector: "Education" },
    { name: "Silver City Search and Rescue", ein: "38-4455669", sector: "Public & Societal Benefit" },
    { name: "Ontonagon Township Library", ein: "38-5566776", sector: "Education" }
  ],
  'Keweenaw County': [
    { name: "Keweenaw County Historical Society", ein: "38-1122337", sector: "Arts & Culture" },
    { name: "Grant Township Parks and Rec NP", ein: "38-2233448", sector: "Environment & Animals" },
    { name: "Keweenaw Mountain Lodge Preservation", ein: "38-3344559", sector: "Arts & Culture" },
    { name: "Bete Grise Preserve (Friends of)", ein: "38-4455665", sector: "Environment & Animals" }
  ]
};